# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  bugstack虫洞栈
subtitle: 沉淀、分享、成长，让自己和他人都能有所收获
name: bugstack虫洞栈
email: 184172133@qq.com
description: 沉淀、分享、成长，专注于原创专题案例，以最易学习编程的方式分享知识，让自己和他人都能有所收获。目前已完成的专题有；Netty4.x实战专题案例、用Java实现JVM、基于JavaAgent的全链路监控、手写RPC框架、DDD专题案例等。
keywords: Java,Java教程,程序人生,程序员,前端,Web,全栈
encoding: "utf-8"
favicon: favicon.ico 

repository: fuzhengwei/fuzhengwei.github.io
github_url: https://github.com/fuzhengwei
url: https://fuzhengwei.github.io
enforce_ssl: fuzhengwei.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /zsxq.html
    label: 星球
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home
  -
    href: /itstack-demo-netty.html
    label: Netty4.x专题
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: 入门篇

      -
        subHref: /spring-cloud.html
        subLabel: 拓展篇
  -
    href: /java.html
    label: Java
    target: _self

  -
    href: /web.html
    label: 前端
    target: _self

  -
    href: /life.html
    label: 程序人生
    target: _self


  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /open-source.html
    label: Git仓库
    target: _blank

  -
    href: /gitchat.html
    label: GitChat
    target: _blank

  -
    href: /geektime.html
    label: 极客
    target: _blank


# selected articles 精选文章
classes:

  -
    href: /life.html
    name: 程序人生
    describe: 程序员的人生不止有代码


  -
    href: /java.html
    name: Java 系列文章
    describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: fuzhengwei
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: fuzhengwei
  repo: fuzhengwei.github.io
  oauth:
    client_id: 61bfc53d957e74e78f8f
    client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: fuzhengwei
  repo: fuzhengwei.github.io
  clientID: df8beab2190bec20352a
  clientSecret: 7eeeb4369d699c933f02a026ae8bb1e2a9c80e90
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
