# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bugstack虫洞栈 | 沉淀、分享、成长，让自己和他人都能有所收获 # ex. I m Chuan
subtitle: 沉淀、分享、成长，让自己和他人都能有所收获
name: bugstack虫洞栈 # ex. DONGChuan
email: 184172133@qq.com
location: Beijing, China # ex. Nice, France
company: MyCompany
company_url: my_company_website
github_url: https://github.com/fuzhengwei # ex. https://github.com/DONGChuan
github_username: fuzhengwei # ex. DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://fuzhengwei.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: fuzhengwei
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: fuzhengwei
  repo: fuzhengwei.github.io
  oauth:
    client_id: 61bfc53d957e74e78f8f
    client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: fuzhengwei
  repo: fuzhengwei.github.io
  clientID: df8beab2190bec20352a
  clientSecret: 7eeeb4369d699c933f02a026ae8bb1e2a9c80e90
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true